name: Build

# Controls when the workflow will run
on:
  push:
    branches:
      - master

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: "Tag Name"
        required: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

      - name: tsc compile
        run: npm run tscc

      - name: tsc compile with declarationMap
        run: npm run tsccd

      - name: Code Linting
        run: npm run lint

      - name: Build Grammar from yaml to json
        run: npm run bg

      - name: build with webpack
        run: npm run webpackp

      - name: build with esbuild
        run: npm run esbuildp
