name: Build and Test

# Controls when the workflow will run
on:
  push:
    branches:
      - master

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: "Tag Name"
        required: false

  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: tsc compile
        run: npm run tscc

      - name: tsc compile with declarationMap
        run: npm run tsccd

      - name: Code Linting
        run: npm run lint

      - name: Build Grammar from yaml to json
        run: npm run bg

      - name: build with webpack
        run: npm run webpackp

      - name: clean webpackp
        run: rm -rf ./dist

      - name: build with esbuild
        run: npm run esbuildp

  test:
    uses: ./.github/workflows/test.yml
