name: vsce Publish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: "Tag Name"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    name: publish
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Package web extension
        run: npm run vscode:prepublish

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: run vsce publish
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: print tag
        env:
          TAGS: ${{ github.event.inputs.tags }}
        run: |
          echo "[$TAGS] publish completed."
