name: vsce Package

# Controls when the workflow will run
on:
  push:
    branches:
      - master

  pull_request:

  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: "Tag Name"
        required: false

  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "package"
  package:
    name: package
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      #- name: Build Grammar from yaml to json
      #  run: npm run bg

      - name: Package web extension
        run: npm run vscode:prepublish

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: run vsce package
        run: npm run package

      - name: Archive vsix production
        uses: actions/upload-artifact@v4
        with:
          name: vsix production
          path: ./*.vsix
          if-no-files-found: error

      - name: print tag
        env:
          TAGS: ${{ github.event.inputs.tags }}
        run: |
          echo "[$TAGS] build completed."
