name: vsce Publish Pre-release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Tag Name"
        required: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish_pre:
    name: publish pre-release
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Package web extension
        run: npm run vscode:prepublish

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: run vsce publish with pre-release flag
        run: npm run publish-pre
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: print tag
        env:
          TAGS: ${{ github.event.inputs.tags }}
        run: |
          echo "[$TAGS] publish with pre-release completed."
